
INSERT INTO `articles`(`article_id`, `image_id`, `user_id`, `categorie_id`, `subcategorie_id`, `title`, `description`, `content`, `state`, `views`, `shared`, `url`, `registration_date`, `last_time_update`) VALUES
  (0,1,2,1,1,"Aprende a programar facil y rapido","description","JSON",0,0,0,"aprende-a-programar-facil-y-rapido",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,2,"¿Que es xamarin studio?, ¿Como usarlo?","description","JSON",0,0,0,"¿Que-es-xamarin-studio?-¿Como-usarlo?",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,2,"Aplicaciones Android con xamarin","description","JSON",0,0,0,"aplicaciones-android-con-xamarin",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,3,"Aprende Java desde cero facil","description","JSON",0,0,0,"aprende-java-desde-cero-facil",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,3,"¿Java es el mejor lenguaje para aprender a programar?","description","JSON",0,0,0,"java-es-el-mejor-lenguaje-para-aprender-a-programar",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,4,"Objetos del dom ¿Como se usan?","description","JSON",0,0,0,"objetos-del-dom-como-se-usan",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,4,"Ajax con JavaScript puro","description","JSON",0,0,0,"ajax-con-javascript-puro",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

  (0,2,2,2,4,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-s-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

  (0,1,2,1,5,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-te-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,5,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,5,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-se-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,1,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-ter-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cua-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,2,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qui-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,2,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-sex-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,1,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-tercer-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,1,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cuarto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,2,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-quinto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,2,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-sexto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,3,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-t-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,3,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-c-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,4,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-q-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,4,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-s-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,5,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-te-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,5,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,5,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-se-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,1,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-ter-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cua-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,2,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qui-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,2,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-sex-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,1,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-tercer-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,1,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cuarto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,2,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-quinto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,2,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-sexto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,3,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-t-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,3,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-c-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,4,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-q-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,4,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-s-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,5,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-te-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,5,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,5,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-se-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,1,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-ter-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cua-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,2,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qui-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,2,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-sex-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,1,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-tercer-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,1,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cuarto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,2,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-quinto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,2,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-sexto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,3,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-t-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,3,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-c-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,4,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-q-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,4,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-s-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,5,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-te-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,5,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,5,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-se-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,1,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-ter-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cua-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,2,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qui-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,2,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-sex-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,1,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-tercer-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,1,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cuarto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,2,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-quinto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,2,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-sexto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,3,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-t-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,3,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-c-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,4,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-q-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,4,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-s-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,5,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-te-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,5,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,5,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-se-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,1,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-ter-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cua-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,2,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qui-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,2,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-sex-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,1,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-tercer-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,1,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cuarto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,2,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-quinto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,2,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-sexto-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,3,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-t-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,3,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-c-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,4,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-q-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,4,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-s-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,5,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-te-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,1,5,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,1,5,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qu-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-se-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,1,"Este es el titulo de mi tercer post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-ter-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,1,"Este es el titulo de mi cuarto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-cua-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,1,2,2,2,"Este es el titulo de mi quinto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-qui-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  (0,2,2,2,2,"Este es el titulo de mi sexto post","description","JSON",0,0,0,"este-es-el-titulo-de-mi-sex-post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
